### ISSUE TITLE
cryptnono BPF fails to compile with kernel 7.0.0

### ISSUE THREAD

**Issue by manics** [cryptnono/cryptnono#100]
Ubuntu 26.04.1 LTS includes Linux kernel 7.0.0

Cryptnono's BPF program fails to compile on this kernel. execwhacker logs:
```
/usr/lib/python3/dist-packages/traitlets/config/configurable.py:478: UserWarning: ExecWhacker.log should be a Logger or LoggerAdapter, got <BoundLoggerLazyProxy(logger=None, wrapper_class=None, processors=None, context_class=None, initial_values={}, logger_factory_args=())>.
  warnings.warn(
{"event": "Found 2 substrings to check process cmdlines for", "level": "info", "timestamp": "2026-09-13T21:22:13.578169Z"}
{"event": "Found 2 patterns to explicitly allow", "level": "info", "timestamp": "2026-09-13T21:22:13.578225Z"}
{"event": "Compiling and loading BPF program...", "level": "info", "timestamp": "2026-09-13T21:22:13.578287Z"}
In file included from /virtual/main.c:9:
include/linux/fs.h:2429:2: warning: declaration does not declare anything [-Wmissing-declarations]
 2429 |         struct __filename_head;
      |         ^~~~~~~~~~~~~~~~~~~~~~
include/linux/fs.h:2433:15: error: static assertion failed due to requirement 'sizeof(struct filename) % 64 == 0': sizeof(struct filename) % 64 == 0
 2433 | static_assert(sizeof(struct filename) % 64 == 0);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/build_bug.h:79:50: note: expanded from macro 'static_assert'
   79 | #define static_assert(expr, ...) __static_assert(expr, ##__VA_ARGS__, #expr)
      |                                                  ^~~~
include/linux/build_bug.h:80:56: note: expanded from macro '__static_assert'
   80 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
include/linux/fs.h:2433:44: note: expression evaluates to '40 == 0'
 2433 | static_assert(sizeof(struct filename) % 64 == 0);
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
include/linux/build_bug.h:79:50: note: expanded from macro 'static_assert'
   79 | #define static_assert(expr, ...) __static_assert(expr, ##__VA_ARGS__, #expr)
      |                                                  ^~~~
include/linux/build_bug.h:80:56: note: expanded from macro '__static_assert'
   80 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
1 warning and 1 error generated.
Traceback (most recent call last):
  File [35m"/scripts/execwhacker.py"[0m, line [35m565[0m, in [35m<module>[0m
    [31mapp.start[0m[1;31m()[0m
    [31m~~~~~~~~~[0m[1;31m^^[0m
  File [35m"/scripts/execwhacker.py"[0m, line [35m501[0m, in [35mstart[0m
    b = BPF(text=bpf_text)
  File [35m"/usr/lib/python3/dist-packages/bcc/__init__.py"[0m, line [35m507[0m, in [35m__init__[0m
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
[1;35mException[0m: [35mFailed to compile BPF module <text>[0m
Exception ignored while calling deallocator <function Application.__del__ at 0x73c194461c70>:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 1066, in __del__
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 1055, in close_handlers
  File "/usr/lib/python3/dist-packages/structlog/_config.py", line 425, in __getattr__
AttributeError: 'BoundLoggerFilteringAtInfo' object has no attribute 'handlers'
```
